import React from "react";

export const strings = {
    'Home': 'Home',
    'About': 'About',
    'Online Classes': 'Private Classes',
    'Workshops': 'Workshops',
    'Blog': 'Blog',
    'Language': 'Language',
    'Contact Us': 'Contact Us',
    'Dashboard': 'Dashboard',
    'Login': 'Login',
    'Group Classes':'Group Classes',
    'Logout': 'Logout',
    'Sign Up': 'Sign Up',
    'Our Services': 'Our Services',
    'Online Music Lessons for Kids': 'Online Music Lessons for Kids',
    'Blog Last Articles': 'Blog Last Articles',
    'Teaching Team': 'Teaching Team',
    'Upcoming Online Workshops': 'Upcoming Online Workshops',
    'Rhythmitica Staffs': 'Our Team',
    'About Rhythmitica Kids': 'About Rhythmitica Kids',
    'Teachers': 'Teachers',
    'Categories': 'Categories',
    'An error occurred when receiving data!': '',
    'Search in blog...': 'Search in blog...',
    
    'Couldn\'t find anything!': 'Couldn\'t find anything!',
    'Contact Details': 'Contact Details',
    'Send Message': 'Send Message',
    'Email': 'Email',
    'Subject': 'Subject',
    'Your Message': 'Your Message',
    'Name': 'Name',
    'Age': 'Age',
    'Family': 'Family',
    'Teachers Of This Lesson': 'Teachers',
    'Read more...': 'Read more...',
    'Reserve Class': 'Reserve Class',
    'Packages Of This Teacher': 'Packages',
    'Reserve': 'Book Private Lessons',
    'Checkout': 'Learn more',
    'Teachers Count': 'Teachers Count',
    'Duration': 'Duration',
    'Price': 'Price',
    'Details': 'Details',
    'Time': 'Time',
    'Book': 'Book',
    'min': 'min',
    'by': 'by',
    'Tuition Fee': 'Tuition Fee',
    'Code Discount': 'Code Discount',
    'Sessions Discount': 'Sessions Discount',
    'Total Tuition': 'Total Tuition',
    'Timezone': 'Timezone',
    'Selected Date and Time': 'Selected Date and Time',
    'Sessions Count': 'Sessions Count',
    'Session': 'Session',
    'Sessions': 'Sessions',
    'Coupon': 'Coupon',
    'Redeem': 'Redeem',
    'Available': 'Available',
    'Yes': 'Yes',
    'No': 'No',
    'discount': 'discount',
    'Discount Code': 'Discount Code',
    'validate': 'validate',
    'Selected Day\'s Class Times': 'Selected Day\'s Class Times',
    'Choose The Day!': 'Choose The Day!',
    'Next sessions will be set weekly': 'Next sessions will be set weekly',
    'Class Times': 'Course Schedule',
    'Class Name': 'Class Name',
    'Discount': 'Discount',
    'I Accept the terms.': 'I Accept the terms.',
    'Terms': 'Terms',
    'I do not Accept': 'I do not Accept',
    'I Accept': 'I Accept',
    'Type': 'Type',
    'Enroll': 'Enroll',
    'Capacity': 'Capacity',
    'Repeat Password': 'Repeat Password',
    'Password': 'Password',
    'Repeat New Password': 'Repeat New Password',
    'New Password': 'New Password',
    'Enter the new password': 'Enter the new password',
    'I Forgot My Password': 'I Forgot My Password',
    'Do not have an account?': 'Do not have an account?',
    'Already have an account?': 'Already have an account?',
    'Fill in the whole fields.': 'Fill in the whole fields.',
    'Invalid Email!': 'Invalid Email!',
    'Password must be at least 8 characters': 'Password must be at least 8 characters',
    'Name and Family must have at list 3 characters': 'Name and Family must have at list 3 characters',
    'Passwords do not match': 'Passwords do not match',
    'Your account was created successfully. To activate your account, checkout your Email Inbox. If you do not see anything, then checkout your spam messages.': 'Your account was created successfully. To activate your account, checkout your Email Inbox. If you do not see anything, then checkout your spam messages.',
    'Remember Me': 'Remember Me',
    'This Email Exists!': 'This Email Exists!',
    'Invalid Email or Password!': 'Invalid Email or Password!',
    'Enter Your Email Address.': 'Enter Your Email Address.',
    'After pressing the "Send Code" button, you\'ll receive an email containing a code, and you have to enter that code in the next step.': 'After pressing the "Send Code" button, you\'ll receive an email containing a code, and you have to enter that code in the next step.',
    'Send Code': 'Send Code',
    'Enter the code': 'Enter the code',
    'If you do not see any thing in you Inbox, checkout your spam emails before pressing the re-send button.': 'If you do not see any thing in you Inbox, checkout your spam emails before pressing the re-send button.',
    'After this step, your password will change to this new password.': 'After this step, your password will change to this new password.',
    'Done': 'Done',
    'Your password was successfully changed to this new password. Now you can Login with your new password.': 'Your password was successfully changed to this new password. Now you can Login with your new password.',
    'Unfortunately a problem occurred. Please try later.': 'Unfortunately a problem occurred. Please try later.',
    'Go to login page': 'Go to login page',
    'Retry': 'Retry',
    'Coupon is not valid': 'Coupon is not valid',
    'Could not get your Timezone! Please select it in "details" section.': 'Could not get your Timezone! Please select it in "details" section.',
    'First Accept the terms of services.': 'First Accept the terms of services.',
    'Ordered successfully': 'Ordered successfully',
    'Could not order!': 'Could not order!',
    'You can use discount code just for less than 8 sessions.': 'You can use discount code just for less than 8 sessions.',
    'Invalid Discount Code': 'Invalid Discount Code',
    'Discount code applied successfully.': 'Discount code applied successfully.',
    'Please Complete your profile.': 'Please Complete your profile.',
    'Invalid Email': 'Invalid Email',
    'An Error Occurred': 'An Error Occurred',
    'Password length can not be less than 8 characters': 'Password length can not be less than 8 characters',
    'Passwords are not same': 'Passwords are not same',
    'First select date and time': 'First select date and time',



    variables: {
        footerAboutText: 'Rhythmitica is the very first world online music academy established in 2015 based in Toronto, Canada. The academic tutoring of traditional world music to interested students across the globe and promoting world music are the main goals of Rhythmitica.',
        home: 'Toronto, ON - CANADA',
        phone: '+1-855-531-0127',
        email: 'kids@rhythmitica.com',
        website: 'www.rhythmitica.com',
        aboutPageText: 'The "Rhythmitica Kids" offers Persian music lessons for children and youth ages 3 to 12 across a variety of instruments, through our unique live online system. At the "Rhythmitica Kids" you can take Daf & Rhythm lessons, Persian Tar lessons, Kamancheh lessons, Persian/Farsi Language lessons, and even music consultation with the professional instructors.\n' +
            'Rhythmitica Kids is designed to help students as young as three years of age to transition from our early year\'s program at the Elementary, Intermediate, and Advanced levels.',
        termsOfTheWebsite: ' Schedule: \nSessions are\n held on a weekly basis.\n'+'Duration: Duration of each private session is 30 minutes.Rescheduling a session may be requested in case you are not able to attend your regular class.You can simply reschedule through your Student Panel. The deadline for the change request is 24 hours before the start time of your class (according to your time zone).Please notice that, in order to respect our instructors’ valuable time, you are not allowed to reschedule more than one session per month. Unfortunately substitute classes cannot be arranged if you miss your class without rescheduling it prior to the deadline mentioned above.Important Notice: Rescheduling your classes MUST be done ONLY through your online dashboard. Notifying your instructor alone is not an acceptable method of rescheduling, otherwise you will be charged for the missed class. If you have encountered any difficulties to reschedule your class through your dashboard, please email education department as soon as possible (24 hr. before the start time of your class) and we would gladly help to solve the issue to accommodate your request.'
        
    }
};
